# https://taskfile.dev

version: '3'

vars:
  DB_NAME: moxiedb

tasks:
  setup:
    desc: Create both main and test databases
    cmds:
      - task: db:create
      - task: db:create
        vars:
          DB_NAME: moxietestdb

  teardown:
    desc: Drop both main and test databases
    cmds:
      - task: db:drop
      - task: db:drop
        vars:
          DB_NAME: moxietestdb

  start:
    desc: Start FastAPI development server
    cmd: uv run fastapi dev main.py

  test:
    desc: Run tests
    cmd: uv run pytest

  db:create:
    desc: Create PostgreSQL database, schema and sample data
    cmds:
      - createdb {{.DB_NAME}} || echo "Database '{{.DB_NAME}}' already exists or error occurred"
      - psql -d {{.DB_NAME}} -f db/schema.sql
      - psql -d {{.DB_NAME}} -f db/sample_data.sql
      - echo "Database setup complete!"

  db:drop:
    desc: Drop PostgreSQL database
    cmds:
      - dropdb {{.DB_NAME}}
